apiVersion: v1
kind: Secret
metadata:
  name: ghcr-pull-secret
  namespace: cortex-knowledge
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoicnktb3BzIiwicGFzc3dvcmQiOiJnaHBfTWVwWjlZSjlhYzd2V0tuY1lhdXhvUkwyS3BGTHNjNDh2NFR5IiwiYXV0aCI6ImNua3RiM0J6T21kb2NGOU5aWEJhT1ZsS09XRmpOM1pYUzI1aldXRjFlRzlTVERKTGNFWk1jMk0wT0hZMFZIaz0ifX19
