apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: cortex-orchestrator
  name: cortex-orchestrator
  namespace: cortex
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cortex-orchestrator
  sessionAffinity: None
  type: ClusterIP
