apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: youtube-ingestion
  name: youtube-ingestion
  namespace: cortex
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: youtube-ingestion
  sessionAffinity: None
  type: ClusterIP
