apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-pull-secret
  namespace: kube-system
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS0xLmRvY2tlci5pbyI6eyJ1c2VybmFtZSI6InJ5b3BzIiwicGFzc3dvcmQiOiJkY2tyX3BhdF9ybzRtM1llZmxYZU5yYy1fMExZUDJNMXJsaWciLCJhdXRoIjoiY25sdmNITTZaR05yY2w5d1lYUmZjbTgwYlROWlpXWnNXR1ZPY21NdFh6Qk1XVkF5VFRGeWJHbG4ifX19