apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: cortex-csaf
  labels:
    app.kubernetes.io/part-of: cortex
    security.cortex.cortex-io.dev/zone: trusted
    name: cortex-csaf
